name: "\U0001F4A1 New Ticket"
description: Suggest a new task

title: 'your-issue'

body:
  - type: markdown
    attributes:
      value: |
        _Thank you for taking the time to propose a new idea_

  - type: textarea
    id: problem
    attributes:
      label: 'Describe the Problem'
      description: <h4>Please provide a short user story **DESCRIPTION** of the **PROBLEM**</h4)
      placeholder: As a user I...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 'Describe the Proposed Solution'
      description: <h4>Try to provide an EXAMPLE or CONCEPT of a design pattern that will lead to a SOLUTION</h4>
      placeholder: Implementing x, y, & z will...
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 'References'
      description: <h4>Please provide any **SCREENSHOTS**, **CODE SNIPPETS** or **LINKS** to the codebase or documentation which will help implement a solution.</h4>

