connections = [
    ["I lost you to the summer wind", "windy city", "gust of wind", "north wind"],
    ["snake charmer", "snake eyes", "snake along", "see snakes"],
    ["fork in the road", "fork out", "stick a fork in it", "forked tongue"],
    ["go under the knife", "knife's edge", "twist the knife", "at knife's point"],
    ["time flies", "time will tell", "in the nick of time", "killing time"],
    ["on hand", "hand in hand", "lend a hand", "at hand"],
    ["heart of gold", "break someone's heart", "wear your heart on your sleeve", "from the bottom of my heart"],
    ["peace of mind", "change your mind", "speak your mind", "out of sight out of mind"],
    ["play with fire", "on fire", "out of the frying pan into the fire", "fire away"],
    ["head over heels", "keep your head above water", "lose your head", "over my head"],
    ["catch your eye", "in the blink of an eye", "eye for an eye", "keep an eye on"],
    ["in hot water", "water under the bridge", "test the waters", "blood is thicker than water"],
    ["put your foot down", "foot the bill", "get off on the right foot", "put your best foot forward"],
    ["word of mouth", "mark my words", "have the last word", "a man of his word"],
    ["back to square one", "turn your back on", "back and forth", "behind your back"],
    ["in the dark", "a shot in the dark", "kept in the dark", "out of the dark"],
    ["bite the bullet", "bite your tongue", "bite off more than you can chew", "once bitten twice shy"],
    ["cold shoulder", "in cold blood", "cold as ice", "out cold"],
    ["break the ice", "ice in your veins", "walk on thin ice", "on ice"],
    ["on the same page", "turn the page", "page-turner", "a blank page"],
    ["in a nutshell", "crack the nut", "hard nut to crack", "tough nut to crack"],
    ["roll the dice", "the dice are cast", "no dice", "loaded dice"],
    ["come clean", "clean as a whistle", "a clean slate", "a clean break"],
    ["hit the nail on the head", "a nail-biter", "as tough as nails", "nail down"],
    ["hit the ground running", "hit or miss", "hit the sack", "hit the jackpot"],
    ["on the ball", "get the ball rolling", "drop the ball", "ballpark figure"],
    ["up in the air", "walking on air", "clear the air", "air your dirty laundry"],
    ["through thick and thin", "thick as thieves", "a thick skin", "in the thick of it"],
    ["in the same boat", "miss the boat", "rock the boat", "boatswain’s cry"],
    ["on the line", "draw the line", "hold the line", "walk the line"],
    ["pull the plug", "plugged in", "plug away", "pull the wool over your eyes"],
    ["under the weather", "weather the storm", "fair-weather friend", "in all weather"],
    ["a piece of cake", "icing on the cake", "have your cake and eat it too", "sell like hotcakes"],
    ["out of the blue", "blue moon", "blue blood", "once in a blue moon"],
    ["spill the beans", "full of beans", "not worth a hill of beans", "cool beans"],
    ["on the fence", "mend fences", "fence-sitter", "sit on the fence"],
    ["break the bank", "bank on it", "laugh all the way to the bank", "bank balance"],
    ["cut corners", "a cut above", "cut to the chase", "cut and dried"],
    ["under your nose", "keep your nose clean", "nose to the grindstone", "poke your nose into"],
    ["in hot water", "water down", "water off a duck's back", "like water"],
    ["on the ropes", "rope into", "at the end of your rope", "give someone enough rope"],
    ["drop in the bucket", "kick the bucket", "bucket list", "drop the ball"],
    ["make ends meet", "at the end of the day", "at your wit's end", "burn the candle at both ends"],
    ["down to earth", "come down with", "down in the dumps", "down the rabbit hole"],
    ["draw a blank", "blank slate", "mind went blank", "fill in the blank"],
    ["keep in touch", "lose touch", "touch base", "out of touch"],
    ["ring a bell", "give someone a ring", "run rings around", "throw your hat in the ring"],
    ["run out of steam", "run its course", "run amok", "run into trouble"],
    ["play it by ear", "lend an ear", "fall on deaf ears", "music to your ears"],
    ["steal the show", "steal someone's thunder", "steal your heart", "steal the spotlight"],
    ["under the radar", "fly under the radar", "on the radar", "off the radar"],
    ["take the plunge", "take a rain check", "take it easy", "take a back seat"],
    ["hold your horses", "hold your breath", "hold the line", "hold it together"],
    ["in the driver's seat", "backseat driver", "drive someone up the wall", "drive a hard bargain"]
]